### ISSUE TITLE
v0.4.2 does not build anymore?

### ISSUE THREAD

**Issue by comfix** [CherryMace/melvor-mod-manager#13]
Hi there,
for starters I never worked with VueJS and or their deployments before, so bare with me :)

I tried building the release as well as master with NodeJS v18.7.0 on Arch.

I do get the message `Build complete. The dist_electron/bundled directory is ready to be deployed.` but then the build fails with those two errors: 

```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                                            5:28:45 PM

 error  in ./node_modules/htmlparser2/lib/esm/index.js

Module parse failed: Unexpected token (59:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return getFeed(parseDOM(feed, options));
| }
> export * as DomUtils from "domutils";
| // Old name for DomHandler
| export { DomHandler as DefaultHandler };

 @ ./node_modules/cheerio/lib/esm/index.js 11:0-68 13:6-26
 @ ./src/modsHandler.js
 @ ./src/background.js
 @ multi ./src/background.js

 error  in ./node_modules/parse5/dist/index.js

Module parse failed: Unexpected token (6:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { serialize, serializeOuter } from './serializer/index.js';
| /** @internal */
> export * as foreignContent from './common/foreign-content.js';
| /** @internal */
| export * as html from './common/html.js';

 @ ./node_modules/cheerio/lib/esm/parsers/parse5-adapter.js 2:0-79 22:10-23 23:10-23 48:18-32
 @ ./node_modules/cheerio/lib/esm/index.js
 @ ./src/modsHandler.js
 @ ./src/background.js
 @ multi ./src/background.js

Unhandled rejection Error: Build failed with errors.Completed in 1ms
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/vue-cli-plugin-electron-builder/index.js:198:21
    at finalCallback (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compiler.js:271:21)
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/Hook.js:154:20)
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/Hook.js:154:20)
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/Hook.js:154:20)
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at /home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at step (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
    at done (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
    at tryCatcher (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/comfix/Projects/GitHub/melvor-mod-manager-0.4.2/node_modules/bluebird/js/release/promise.js:547:31)
```

I do see some files in `electron_dist` but when I try to test it locally with `serve -s electron_dist/bundled` (as the vue docs provide as an example) I do only get a "blank page" with the content of the index.html in `bundled`. Also running `npm run electron:serve` fails with the two errors shown earlier.

Am I missing something or broke some library?

Help on this would be really appreciated.

**Comment by TheNumberOne** [comment]
I got this error as well.
