### ISSUE TITLE
m3-icon.png needs to be at least 512x512 to build on MacOS

### ISSUE THREAD

**Issue by s0hanian** [CherryMace/melvor-mod-manager#3]
I resized it myself and it built fine after, but you may want to provide a properly sized png.

Stack Trace/Error Msg if it matters:
`InvalidConfigurationError: image /Users/sarah/Downloads/melvor-mod-manager/build/m3-icon.png must be at least 512x512
    at MacPackager.resolveIcon (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/platformPackager.ts:682:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at MacPackager.getOrConvertIcon (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/platformPackager.ts:640:20)
    at MacPackager.applyCommonInfo (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/macPackager.ts:375:18)
    at Object.createMacApp (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/electron/electronMac.ts:122:3)
    at beforeCopyExtraFiles (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/electron/ElectronFramework.ts:86:5)
    at MacPackager.doPack (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/platformPackager.ts:271:7)
    at MacPackager.pack (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/sarah/Downloads/melvor-mod-manager/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/sarah/Downloads/melvor-mod-manager/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/sarah/Downloads/melvor-mod-manager/node_modules/builder-util/src/promise.ts:12:14) {
  code: 'ERR_ICON_TOO_SMALL'
}`

**Comment by ChaseStrackbein** [comment]
There actually is a 512px x 512px icon found at src/assets/m3.png that you can replace the one found in the build folder with.

My original reason for using the smaller one was that I felt that It looked (slightly) better on Windows since it didn't have to downscale so much, but seeing as it's actually throwing an error for macOS I'll go ahead and put it back.

**Comment by ChaseStrackbein** [comment]
Updated the icon size to 512x512
